### ISSUE TITLE
请问Android ebpf 如何解决权限问题？

### ISSUE THREAD

**Issue by lysShub** [runningforlife/runningforlife.github.io#1]
看到你的这篇 [文章](https://sniffer.site/2021/11/26/%E7%90%86%E8%A7%A3android-ebpf/) ，想问一下如何解决权限问题，因为大部分都要root权限

**Comment by runningforlife** [comment]
目前Android的实现都是需要root权限 最新的Android S已经增加了相关的权限控制 ， 可以参考下源码:

#define DEFINE_BPF_PROG_KVER_RANGE_OPT(SECTION_NAME, prog_uid, prog_gid, the_prog, min_kv, max_kv, \
                                       opt)                                                        \
    const struct bpf_prog_def SEC("progs") the_prog##_def = {                                      \
            .uid = (prog_uid),                                                                     \
            .gid = (prog_gid),                                                                     \
            .min_kver = (min_kv),                                                                  \
            .max_kver = (max_kv),                                                                  \
            .optional = (opt),                                                                     \
            .bpfloader_min_ver = DEFAULT_BPFLOADER_MIN_VER,                                        \
            .bpfloader_max_ver = DEFAULT_BPFLOADER_MAX_VER,                                        \
    };                                                                                             \
    SEC(SECTION_NAME)                                                                              \
    int the_prog

**Comment by runningforlife** [comment]
> 看到你的这篇 [文章](https://sniffer.site/2021/11/26/%E7%90%86%E8%A7%A3android-ebpf/) ，想问一下如何解决权限问题，因为大部分都要root权限
